[package]
name = "gemini-client-api"
version = "2.4.8"
edition = "2024"
repository = "https://github.com/Suryansh-Dey/llms-client"
authors = ["Suryansh Dey suryanshdey@gmail.com"]
keywords = ["Gemini", "SDK", "client", "API", "AI"]
description = "Rust SDK to easily use streaming api will all tools(code, search, function calling) of Gemini"
readme = "README.md"
license = "MIT"

[dependencies]
actix-web = "4"
awc = { version = "3", features = ["rustls"] }
base64 = "0.22.1"
derive-new = "0.7.0"
futures = "0.3.31"
getset = "0.1.5"
pin-project-lite = "0.2.16"
regex = "1.11.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1", features = ["fs"] }
